[project]
name = "smart-weather"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi-mcp>=0.4.0",
    "fastapi[standard]>=0.139.2",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "tortoise-orm>=1.1.7",
]
[tool.fastapi]
entrypoint = "app.main:app"
