"""Token families on access tokens; client-scoped weather history.

Generated by makemigrations, then hand-edited to work around two gaps in
tortoise-orm 1.1.8's schema editor (the resulting migration state is unchanged,
so makemigrations still reports no changes):

* AddField never creates the index for a field declared with index=True, so
  access_tokens.family_id would have had no index. AddIndexedField creates it.
* On SQLite, RemoveField of a foreign key rebuilds the table but keeps the
  column, so downgrading would leave weather_lookups.client_id behind.
  AddForeignKey rebuilds from the pre-migration model instead.
* On SQLite, AlterField rebuilds the whole table (copy, drop, rename), which
  drops every index on it and still does not create the new one. Only the index
  changed on weather_lookups.created_at, so AlterFieldIndex adds just that index.

Downgrading is supported: indexes are dropped before the columns that use them,
and on SQLite family_id is removed with ALTER TABLE ... DROP COLUMN instead of a
table rebuild that would silently drop access_tokens' other indexes.
"""

from tortoise import fields, migrations
from tortoise.fields.base import OnDelete
from tortoise.indexes import Index
from tortoise.migrations import operations as ops
from tortoise.migrations.schema_editor import SqliteSchemaEditor


def _field_index(model, field_name: str) -> Index:
    field = model._meta.fields_map[field_name]
    return Index(fields=(field.source_field or field_name,))


class AddIndexedField(ops.AddField):
    """AddField for a plain (non-relational) field that also creates its index."""

    async def database_forward(self, app_label, old_state, new_state, state_editor=None):
        await super().database_forward(app_label, old_state, new_state, state_editor)
        if state_editor:
            model = new_state.apps.get_model(f"{app_label}.{self.model_name}")
            await state_editor.add_index(model, _field_index(model, self.name))

    async def database_backward(self, app_label, old_state, new_state, state_editor=None):
        if not state_editor:
            return
        model = old_state.apps.get_model(f"{app_label}.{self.model_name}")
        await state_editor.remove_index(model, _field_index(model, self.name))
        if isinstance(state_editor, SqliteSchemaEditor):
            await state_editor._run_sql(
                state_editor.DELETE_FIELD_TEMPLATE.format(
                    table=state_editor._qualify_table_name(model._meta.db_table, model._meta.schema),
                    column=model._meta.fields_db_projection[self.name],
                )
            )
        else:
            await super().database_backward(app_label, old_state, new_state, state_editor)


class AddForeignKey(ops.AddField):
    """AddField whose SQLite downgrade actually removes the FK column.

    Tortoise's SQLite table rebuild for RemoveField copies the FK column back
    into the new table, so rebuild from the pre-migration model instead.
    """

    async def database_backward(self, app_label, old_state, new_state, state_editor=None):
        if isinstance(state_editor, SqliteSchemaEditor):
            await state_editor._remake_table(
                new_state.apps.get_model(f"{app_label}.{self.model_name}")
            )
        else:
            await super().database_backward(app_label, old_state, new_state, state_editor)


class AlterFieldIndex(ops.AlterField):
    """AlterField that changes only a field's index flag (False -> True)."""

    async def database_forward(self, app_label, old_state, new_state, state_editor=None):
        if state_editor:
            model = new_state.apps.get_model(f"{app_label}.{self.model_name}")
            await state_editor.add_index(model, _field_index(model, self.name))

    async def database_backward(self, app_label, old_state, new_state, state_editor=None):
        if state_editor:
            model = old_state.apps.get_model(f"{app_label}.{self.model_name}")
            await state_editor.remove_index(model, _field_index(model, self.name))


class Migration(migrations.Migration):
    dependencies = [('models', '0001_initial')]

    initial = False

    operations = [
        AddIndexedField(
            model_name='AccessToken',
            name='family_id',
            field=fields.CharField(null=True, db_index=True, max_length=64),
        ),
        # Before the index operations below so that, in reverse, the SQLite table
        # rebuild that removes this FK column happens after they are dropped.
        AddForeignKey(
            model_name='WeatherLookup',
            name='client',
            field=fields.ForeignKeyField('models.ApiClient', source_field='client_id', null=True, db_constraint=True, to_field='id', related_name='weather_lookups', on_delete=OnDelete.CASCADE),
        ),
        AlterFieldIndex(
            model_name='WeatherLookup',
            name='created_at',
            field=fields.DatetimeField(db_index=True, auto_now=False, auto_now_add=True),
        ),
        ops.AddIndex(
            model_name='WeatherLookup',
            index=Index(fields=['client_id', 'created_at']),
        ),
    ]
